config/routes.rb
Landstorycorps::Application.routes.draw do
  resources :stories
  devise_for :users

  root 'static_pages#index'

  get 'location/:long/:lat/:vicinity/:storyname' => 'stories#location_stories',
    :constraints => {
      :long => /[+-]?\d+\.\d+/,
      :lat => /[+-]?\d+\.\d+/,
      :vicinity => /.*/,
      :storyname => /.*/
    }

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :users, :foreign_key => "user_id"
  mount_uploader :storyfile, StoryFileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def location
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_action :set_flash_params, only: [:show, :edit, :update, :create, :location_stories]


  # GET /stories
  # GET /stories.json
  def index
    @stories = current_user.stories
  end

  def location_stories
    puts flash[:long]
    puts flash[:lat]
    puts flash[:vicinity]
    puts flash[:storyname]

    # get route params
    lat = flash[:lat]
    long = flash[:long]
    @storyname = unescape flash[:storyname]
    @vicinity = unescape flash[:vicinity]

    #retrieve data from Model
    @stories = current_user.stories.where(:latitude => lat, :longitude => long);
    # @otherstories = Story.where(:latitude => @lat, :longitude => @long);
    @otherstories = Story.all

  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    puts "current user id: #{current_user.id}"
    puts "story user id: #{@story.user_id}"
    # unless current_user.id == @story.user_id
    #   flash[:notice] = "You may only view your own products."
    #   redirect_to root_path
    # end
  end

  # GET /stories/new
  def new
    puts flash[:long]
    puts flash[:lat]
    puts flash[:vicinity]
    puts flash[:storyname]

    @lat = flash[:lat]
    @long = flash[:long]
    @storyname = flash[:storyname]
    @vicinity = flash[:vicinity]

    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  def audio

  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    puts "params: #{story_params}"
    @story.user_id = current_user.id

    puts flash[:long]
    puts flash[:lat]
    puts flash[:vicinity]
    puts flash[:storyname]

    prev_location = "/location/#{@story.longitude}/#{@story.latitude}/#{escape @story.vicinity}/#{escape @story.storyname}"


# u.avatar = params[:file]
# u.avatar = File.open('somewhere')
# u.save!
# u.avatar.url # => '/url/to/file.png'
# u.avatar.current_path # => 'path/to/file.png'
# u.avatar.identifier # => 'file.png'

    respond_to  do |format|
      if @story.save
        format.html { redirect_to prev_location, notice: 'Story was successfully created.' }
        format.json { render action: 'show', status: :created, location: @story }
      else
        format.html { render action: 'new' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    puts flash[:lat]
    puts flash[:long]
    puts flash[:vicinity]
    puts flash[:storyname]
    if @story
      @story.destroy
    end
    respond_to do |format|
      # format.html { redirect_to root_path }

      format.html { redirect_to "/location/#{flash[:lat]}/#{flash[:long]}/#{escape flash[:vicinity]}/#{escape flash[:storyname]}",
                    notice: 'Story was successfully Deleted.'
      }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      begin
        @story = Story.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        @story = nil
      end
    end

    def set_flash_params
      flash[:vicinity] = params[:vicinity]
      flash[:storyname] = params[:storyname]
      flash[:lat] = params[:lat]
      flash[:long] = params[:long]
    end

    def escape item
      Rack::Utils.escape(item)
    end

    def unescape item
      Rack::Utils.unescape(item)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :storyfile,:storyfile_cache,:latitude, :longitude, :storyname, :vicinity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Landstorycorps</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<!--   <%= javascript_include_tag "application", "data-turbolinks-track" => true %> -->
<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="javascript:window.history.back()"><i class="fa fa-arrow-circle-o-left fa-3x"></i></a>
      <a class="brand" href="/"><i class="fa fa-home fa-3x"></i></a>
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, :class => "brand" do %>
          <i class="fa fa-sign-out fa-3x"></i>
        <% end %>
<!--         <a class="brand" href="/users/sign_out" data-method="delete" rel="nofollow"><i class="fa fa-sign-out fa-3x"></i></a> -->
      <% end %>
      <div class="brand" id='appTitle'>VStoryCorps</div>
<!--       <ul class="nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
      </ul> -->
    </div>
  </div>
  <div class="container-fluid">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/index.erb
<div class="row-fluid">
  <div class="span12">
      <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&key=AIzaSyDJLcKc7OSbrmFN6agLkDrF3-r-lburzhk"></script>

      <script type="text/javascript" src="https://maps.googleapis.com/maps/api/place/textsearch/json?query=parks+in+charleston+south+carolina&sensor=false&key=AIzaSyDJLcKc7OSbrmFN6agLkDrF3-r-lburzhk"></script>
      <script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.5/src/infobox.js"></script>
      <!--Sidebar content-->
    <% if user_signed_in? %>

      <div id="name" style="width:inherit;height:inherit">
        <div id="map-canvas"></div>
      </div>

    <% else %>
      <a href="/users/sign_in" class='btn btn-success btn-large btn-block'>Sign In</a>
      <a href="/users/sign_up" class='btn btn-info btn-large btn-block'>Sign Up</a>
    <% end %>

  </div>
</div>

app/views/stories/_form.html.erb
<%= form_for(@story, :html => {:multipart => true}) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :storyfile %><br>
<!--     <%= f.file_field :storyfile, accept:"audio/*", capture:""%> -->
    <%= f.file_field :storyfile%>
  </div>
  <div class="field">
    <%= f.hidden_field :storyfile_cache %>
  </div>
  <div class="field">
    <%= f.hidden_field :latitude, :value => @lat %>
  </div>
  <div class="field">
    <%= f.hidden_field :longitude, :value => @long %>
  </div>
  <div class="field">
    <%= f.hidden_field :storyname, :value => @storyname %>
  </div>
  <div class="field">
    <%= f.hidden_field :vicinity, :value => @vicinity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Storyfile</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.storyfile %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/location_stories.erb
<div class='row-fluid'>
 <div class='span12 '>
    <h2><%= @storyname %></h2>
    <p>
      <%= @vicinity %>
    </p>

    <h1>
      <%= link_to "/stories/new" do %>
        <i class="fa fa-plus-circle fa-2x"></i>
      <% end %>
      Location Stories
    </h1>

    <ul class="media-list">
      <% @stories.each do |story| %>
        <li class="media">
          <%= link_to "/stories/#{story.id}" do %>
            <span class="fa-stack fa-lg media-object pull-left">
              <i class="fa fa-square fa-stack-2x"></i>
              <i class="fa fa-film fa-stack-1x fa-inverse"></i>
            </span>
          <% end %>
          <%= link_to story, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="fa-stack fa-lg media-object pull-left">
              <i class="fa fa-square fa-stack-2x"></i>
              <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
            </span>
          <% end %>
          <%= link_to "/stories/#{story.id}" do %>
            <div class="media-body">
              <h4 class="media-heading"><%= story.title %></h4>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>

<!--     <h2>Stories From Others</h2> -->
    <ul class="media-list">
      <% @otherstories.each do |story| %>
        <li class="media">
          <%= link_to "/stories/#{story.id}" do %>
            <span class="fa-stack fa-lg media-object pull-left">
              <i class="fa fa-square fa-stack-2x"></i>
              <i class="fa fa-film fa-stack-1x fa-inverse"></i>
            </span>
          <% end %>
          <%= link_to story, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="fa-stack fa-lg media-object pull-left">
              <i class="fa fa-square fa-stack-2x"></i>
              <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
            </span>
          <% end %>
          <%= link_to "/stories/#{story.id}" do %>
            <div class="media-body">
              <h4 class="media-heading"><%= story.title %></h4>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>

   </div>
</div>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row-fluid">
  <div class="span12">
    <h3>
      <%= link_to 'Edit', edit_story_path(@story) %>
      <%= @story.title %>
    </h3>

    <%= video_tag(@story.storyfile.url , autoplay: true, controls: true, id: "vidPlayer") %>
  </div>
</div>